template: Hello, %s!
defaultName: Stranger

server:
  #  type: simple
  #  connector:
  #    type: https
  #    jceProvider: Conscrypt
  #port 443 cannot be used if the program is not executed in the name of super user (you need sudo access for ports less than 1024)
  #    port: 8443
  #    keyStorePath: /home/jernej/Documents/certifikati/example.keystore
  #    keyStorePassword: example
  #    validateCerts: false
  applicationConnectors:
    #for HTTP/1.x without TLS
    #    - type: http
    #      port: 8446

    #for HTTP/1.x over TLS
    #    - type: https
    #      port: 8446

    #for HTTP/2 over TLS - https://www.dropwizard.io/1.3.12/docs/manual/configuration.html#http-2-over-tls
    #note that you also need to add dependency dropwizard-http2 in your pom.xml
    - type: http
      port: 8448

  adminConnectors:
    - type: http
      port: 8084

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  # the username
  user: postgres
  # the password
  password: postgres
  # the JDBC URL
  url: jdbc:postgresql://localhost:5433/vedra
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false